// ... existing code ...

app.get('/', (req, res) => {
    // ... existing code ...

    { { res.sendFile(path.resolve(__dirname, 'index.html')); } }

    // ... rest of route function ...
});

// ... rest of code ...